name: Windows CI

on: [push, pull_request]

jobs:
  win:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache
      id:   cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/cache
        key:  dx9-cache
    - name:  Cache create
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
         curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
         7z x _DX2010_.exe DXSDK/Include -o_DX2010_
         7z x _DX2010_.exe DXSDK/Lib/x64 -o_DX2010_
         mv _DX2010_/DXSDK ${{ github.workspace }}/cache
         rm -r _DX2010_*
         dir ${{ github.workspace }}/cache
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/NineTests/CMakeLists.txt'
        configurePreset: default
        configurePresetAdditionalArgs: '[ `-DD3D9_INCLUDE_DIR=${{ github.workspace }}/cache/Include`, `-DD3D9_LIBRARY=${{ github.workspace }}/cache/Lib/x64/d3d9.lib` ]'
        buildPreset: '${{ matrix.configuration }}'
